version: "3"
services:
  server:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/db
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=5000
      - PORT=5000
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]
    restart: on-failure
    volumes:
      - "./:/home/app"
  postgres:
    image: postgres:10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    # expose port for debug purposes
    ports:
      - "8081:5432"